language: r
cache: packages
pandoc_version: 2.1.3

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
    apt:
        packages:
            - libopenblas-base

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
