# Estimations

```{r init, echo = FALSE, message = FALSE}
library(tidyverse)
```

## Coberturas

```{r cober, echo = FALSE, message = FALSE}
completas <- read_csv(
  here::here("results/estimaciones_gto/completas.csv")
) %>% 
  mutate(muestra = "completas")
estrato   <- read_csv(
  here::here("results/estimaciones_gto/faltantes_estrato.csv")
) %>% 
  mutate(muestra = "faltantes_estrato")
casilla   <- read_csv(
  here::here("results/estimaciones_gto/faltantes_casilla.csv")
) %>% 
  mutate(muestra = "faltantes_casilla")
completam <- read_csv(here::here("results/estimaciones_gto/completas_gto_anzarut.csv")) %>% 
  mutate(muestra = "completas")

casillam <- read_csv(here::here("results/estimaciones_gto/faltantes_casilla_gto_anzarut.csv")) %>% 
  mutate(muestra = "faltantes_casilla")

estratom <- read_csv(here::here("results/estimaciones_gto/faltantes_estrato_gto_anzarut.csv")) %>% 
  mutate(muestra = "faltantes_estrato")


real <- quickcountmx::gto_2012 %>% 
    gather(partido, n_votes, pri_pvem:otros) %>% 
    group_by(partido) %>% 
    summarise(n_votes = sum(n_votes)) %>% 
    mutate(rank = rank(-n_votes)) %>% 
    ungroup() %>% 
    mutate(prop_votes = 100 * n_votes / sum(n_votes)) %>% 
    rename(
      party = partido, 
      real  = prop_votes
    )



full_join(completas, estrato) %>% 
  full_join(casilla) %>% 
  full_join(real) %>% 
  # na.omit %>% 
  ggplot(
    aes(
      x = n_muestra
    )
  ) +
  facet_grid(party ~ muestra, scales = "free_y") +
  # geom_point(aes(y = mean_post)) +
  geom_pointrange(
    aes(ymin = int_l, ymax = int_r, y = mean_post),
    alpha = 0.5, fatten = 0.15
  ) +
  theme_minimal() +
  geom_hline(aes(yintercept = real), colour = "red") +
  labs(x = "muestras", y = "est", title = "Binomial Negativa")

full_join(completam, estratom) %>% 
  full_join(casillam) %>% 
  rename(party = partido, int_r = LS, int_l = LI, mean_post = est) %>% 
  full_join(real) %>% 
  # na.omit %>% 
  ggplot(
    aes(
      x = n_muestra
    )
  ) +
  facet_grid(party ~ muestra, scales = "free_y") +
  # geom_point(aes(y = mean_post)) +
  geom_pointrange(
    aes(ymin = int_l, ymax = int_r, y = mean_post),
    alpha = 0.5, fatten = 0.15
  ) +
  theme_minimal() +
  geom_hline(aes(yintercept = real), colour = "red") +
  labs(x = "muestras", y = "est", title = "Mezcla")

```

## Precisiones

```{r, echo = FALSE, message = FALSE}
full_join(completas, estrato) %>% 
  full_join(casilla) %>% 
  na.omit %>% 
  ggplot(
    aes(
      x = n_muestra,
      y = (int_r - int_l)/2
    )
  ) +
  facet_grid(party ~ muestra, scales = "free_y") +
  geom_line() +
  labs(x = "muestras", y = "precision", title = "Binomial Negativa") +
  ylim(0, 1.5) +
  theme_minimal() 

full_join(completam, estratom) %>% 
  full_join(casillam) %>% 
  rename(party = partido, int_r = LS, int_l = LI, mean_post = est) %>% 
  ggplot(
    aes(
      x = n_muestra,
      y = (int_r - int_l) / 2
    )
  ) +
  facet_grid(party ~ muestra, scales = "free_y") +
  geom_line() +
  labs(x = "muestras", y = "precision", title = "Mezcla") +
  ylim(0, 1.5) +
  theme_minimal() 
```

## Comparación

```{R, echo = FALSE, message = FALSE}
bin_neg <- full_join(completas, estrato) %>% 
  full_join(casilla) %>% 
  full_join(real) %>% 
  group_by(party, muestra) %>% 
  summarise(
    ind = sum(if_else(real <= int_r & real >= int_l, 1, 0)),
    pres = mean((int_r - int_l)/2)
  ) %>% ungroup
```


```{r, echo = FALSE, message = FALSE}


mezcla <- full_join(completam, estratom) %>% 
  full_join(casillam) %>% 
  rename(party = partido, int_r = LS, int_l = LI) %>%
  mutate(pres = (int_r - int_l)/2) %>% 
  full_join(real) %>% 
  group_by(party, muestra) %>% 
  summarise(
    ind = sum(if_else(real <= int_r & real >= int_l, 1, 0)),
    pres = mean(pres)
  ) %>% ungroup

mezcla %>% 
  rename(mezcla = ind, pres_mezcla = pres) %>% 
  left_join(
    bin_neg %>% 
      rename(
        bin_neg = ind,
        pres_bin = pres
      )
  ) %>% 
  select(
    party, muestra, mezcla, bin_neg, pres_mezcla, pres_bin
  ) %>% knitr::kable(digits = 2)
```

